* RG-RPG

RG-RPG is a Java-based text, roleplaying-gal game, in which you have to carry
many girls. The RG-RPG acronym is a recursive one and it means "RG-RPG is a Gal
Role playing game Pointing on Girls."

It is developed entirely with emacs(-nox) and it includes a Makefile which uses
plain old javac executable (POJACE). Its main reason to be is my fun and a
growing will to learn emacs from its basics, using it instead of only reading a
book.

I will try to develop this game writing with all the patterns and best practices
I've learnt during years of work and study. I hope you want to play with it when
it is completed, and I hope you will file me any issue or improvement you find
out during this game.


* COPYING

Copyright (C) 2020 Alessandro 'kLeZ' Accardo

This file is part of RG-RPG.

RG-RPG is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

RG-RPG is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with RG-RPG.  If not, see [[http://www.gnu.org/licenses/]].
